server:
  port: 8085

spring:
  config:
    activate:
      on-profile: docker
  application:
    name: sboot.atom.livros
  datasource:
    url: jdbc:postgresql://db:5432/booksontheweb
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver