server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: local
  application:
    name: sboot.atom.livros
  datasource:
    url: jdbc:postgresql://localhost:5432/booksontheweb
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect