name: CI Workflow - Emprestimo

on:
  push:
    branches:
      - 'main'
    paths:
      - 'sboot-atom-emprestimo/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'sboot-atom-emprestimo/**'
  workflow_dispatch:

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -f sboot-atom-emprestimo/pom.xml clean install --no-transfer-progress

      - name: Run Unit Tests
        run: mvn -f sboot-atom-emprestimo/pom.xml test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine Docker Tag
        id: vars
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
          else
            TAG=${GITHUB_SHA::7}
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t rafaelalvezh/sboot-atom-emprestimo:${{ env.TAG }} -f sboot-atom-emprestimo/docker/Dockerfile sboot-atom-emprestimo/
          docker tag rafaelalvezh/sboot-atom-emprestimo:${{ env.TAG }} rafaelalvezh/sboot-atom-emprestimo:latest

      - name: Push Docker Image
        run: |
          docker push rafaelalvezh/sboot-atom-emprestimo:${{ env.TAG }}
          docker push rafaelalvezh/sboot-atom-emprestimo:latest